version: '3.7'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"